# dev/build_shinylive.R
# Build the per-function shinylive apps and export them into one static site.
#
# Plan: four standalone apps, each including the Guide + Data (dataFormat) tabs
# plus a small set of analysis tabs. The full app's app_ui()/app_server() take a
# `tabs` argument, so each app just sources R/ and launches the chosen subset.
#
#   ctt   : Descriptives + CTT
#   irt   : IRT + GRM
#   lca   : LCA + LRA
#   bicl  : Biclustering + IRM
#
# Usage (from the package root):
#   Rscript dev/build_shinylive.R            # assemble all + export all
#   Rscript dev/build_shinylive.R ctt        # assemble all + export only ctt
#   Rscript dev/build_shinylive.R --assemble # assemble dirs only, no export

suppressWarnings(suppressMessages({
  library(shinylive)
}))

root      <- normalizePath(".")
apps_dir  <- file.path(root, "shinylive", "apps")
site_dir  <- file.path(root, "shinylive", "site")

# ---- App definitions -------------------------------------------------------
apps <- list(
  ctt = list(
    tabs    = c("tab_descriptives", "tab_ctt"),
    modules = c("mod_descriptives.R", "mod_ctt.R"),
    title   = "shinyExametrika - CTT"
  ),
  irt = list(
    tabs    = c("tab_irt", "tab_grm"),
    modules = c("mod_irt.R", "mod_grm.R"),
    title   = "shinyExametrika - IRT / GRM"
  ),
  lca = list(
    tabs    = c("tab_lca", "tab_lra"),
    modules = c("mod_lca.R", "mod_lra.R"),
    title   = "shinyExametrika - LCA / LRA"
  ),
  bicl = list(
    tabs    = c("tab_biclustering", "tab_irm"),
    modules = c("mod_biclustering.R", "mod_irm.R"),
    title   = "shinyExametrika - Biclustering / IRM"
  )
)

# Files every app needs (core + shared helpers + Guide/Data/placeholder).
shared_files <- c(
  "app_ui.R", "app_server.R",
  "fct_analysis.R", "fct_precheck.R", "fct_param_help.R", "fct_modelhelp.R",
  "fct_downloads.R", "fct_script.R", "utils_i18n.R",
  "mod_guide.R", "mod_data_upload.R", "mod_placeholder.R"
)

# ---- app.R template --------------------------------------------------------
app_R_template <- function(tabs) {
  tabs_vec <- paste(sprintf('"%s"', tabs), collapse = ", ")
  sprintf('# Auto-generated by dev/build_shinylive.R -- do not edit by hand.
library(shiny)
library(bslib)
library(DT)
library(golem)
library(exametrika)
library(shiny.i18n)
library(shinyjs)
library(shinyWidgets)
if (requireNamespace("ggExametrika", quietly = TRUE)) library(ggExametrika)

# Null-coalescing operator (base R has it from 4.4; define for older webR).
if (!exists("%%||%%")) `%%||%%` <- function(x, y) if (is.null(x)) y else x

# Local inst/ instead of system.file().
app_sys <- function(...) file.path("inst", ...)

# Source all bundled R files.
for (f in list.files("R", pattern = "[.]R$", full.names = TRUE)) {
  source(f, local = TRUE)
}

TABS <- c(%s)
options("golem.app.prod" = TRUE)

shinyApp(
  ui     = function(request) app_ui(request, tabs = TABS),
  server = function(input, output, session) app_server(input, output, session, tabs = TABS)
)
', tabs_vec)
}

# ---- Assemble one app dir --------------------------------------------------
assemble_app <- function(name, spec) {
  dest <- file.path(apps_dir, name)
  unlink(dest, recursive = TRUE)
  dir.create(file.path(dest, "R"), recursive = TRUE, showWarnings = FALSE)

  files <- unique(c(shared_files, spec$modules))
  for (f in files) {
    file.copy(file.path(root, "R", f), file.path(dest, "R", f), overwrite = TRUE)
  }

  # inst/ : i18n, golem-config, www
  dir.create(file.path(dest, "inst", "i18n"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(dest, "inst", "app", "www"), recursive = TRUE, showWarnings = FALSE)
  file.copy(file.path(root, "inst", "i18n", "translation.json"),
            file.path(dest, "inst", "i18n", "translation.json"), overwrite = TRUE)
  file.copy(file.path(root, "inst", "golem-config.yml"),
            file.path(dest, "inst", "golem-config.yml"), overwrite = TRUE)
  www_src <- file.path(root, "inst", "app", "www")
  if (dir.exists(www_src)) {
    for (w in list.files(www_src, full.names = TRUE)) {
      file.copy(w, file.path(dest, "inst", "app", "www", basename(w)), overwrite = TRUE)
    }
  }

  writeLines(app_R_template(spec$tabs), file.path(dest, "app.R"))
  message(sprintf("assembled: %s  [tabs: %s]", name, paste(spec$tabs, collapse = ", ")))
  invisible(dest)
}

# ---- Main ------------------------------------------------------------------
args <- commandArgs(trailingOnly = TRUE)
assemble_only <- "--assemble" %in% args
which_export  <- setdiff(args, "--assemble")
if (length(which_export) == 0) which_export <- names(apps)

dir.create(apps_dir, recursive = TRUE, showWarnings = FALSE)
for (name in names(apps)) assemble_app(name, apps[[name]])

if (assemble_only) {
  message("Assembly done (--assemble): no export.")
} else {
  for (name in which_export) {
    message(sprintf("exporting: %s -> shinylive/site/%s ...", name, name))
    shinylive::export(
      appdir = file.path(apps_dir, name),
      destdir = site_dir,
      subdir = name,
      quiet = FALSE
    )
  }
  message("Export done. Open shinylive/site/<name>/index.html via a static server.")
}
