#' Session R-script log (append-only, timestamped journal)
#'
#' Records, in chronological order across the whole session, the exametrika R
#' code equivalent to what the user did in the GUI, so it can be downloaded as
#' a reproducible script. Every data load and every analysis run appends a new
#' section -- nothing is overwritten -- so the script is a faithful journal of
#' the session. Each section is headed by a divider with a timestamp
#' (YYYY-MM-DD HH:MM:SS) and a short label.
#'
#' The log is an (unnamed) list of entries `list(ts, label, code)`. A
#' reactiveVal holding it lives in app_server and is passed to the data module
#' and every analysis module. Modules call `log_append()`; `assemble_script()`
#' renders the journal. It is session-scoped only (not persisted).
#'
#' @noRd
NULL


#' Append one timestamped section to the session script log
#'
#' @param script_log reactiveVal holding the list (NULL = no-op)
#' @param code character vector of R code lines for this step
#' @param label short section label, e.g. "IRT (2PL)" or "Load sample J15S500"
#' @param ts timestamp string; defaults to the current time
#' @noRd
log_append <- function(script_log, code, label = "",
                       ts = format(Sys.time(), "%Y-%m-%d %H:%M:%S")) {
  if (is.null(script_log)) return(invisible(NULL))
  cur <- script_log()
  cur[[length(cur) + 1L]] <- list(ts = ts, label = label, code = code)
  script_log(cur)
  invisible(NULL)
}


#' Assemble the full reproduction script from the journal
#'
#' @param log_list list of entries `list(ts, label, code)`
#' @param date_str generation date string for the header
#' @return a single character string (the script text)
#' @noRd
assemble_script <- function(log_list, date_str = as.character(Sys.Date())) {
  rule <- paste0("# ", strrep("-", 64))
  header <- c(
    rule,
    "# Reproduction script generated by shinyExametrika",
    paste0("# Generated: ", date_str),
    "#",
    "# A chronological journal of this session. For uploaded data, edit the",
    "# read.csv() path to point to your file.",
    rule,
    "library(exametrika)",
    ""
  )
  if (length(log_list) == 0) {
    return(paste(c(header, "# (no steps recorded yet)"), collapse = "\n"))
  }
  body <- unlist(
    lapply(log_list, function(e) {
      lab <- if (nzchar(e$label %||% "")) paste0("  ", e$label) else ""
      c(
        rule,
        sprintf("# [%s]%s", e$ts, lab),
        rule,
        e$code,
        ""
      )
    }),
    use.names = FALSE
  )
  paste(c(header, body), collapse = "\n")
}


#' Build the data-loading code block for a sample dataset
#' @noRd
script_block_sample <- function(name) {
  c(
    sprintf('data("%s", package = "exametrika")', name),
    sprintf("dat <- %s", name)
  )
}


#' Wrap a character vector of names into indented, quoted, comma-separated lines
#'
#' Keeps each line under `width` characters so long column lists read nicely.
#' Every line except the last gets a trailing comma.
#' @noRd
wrap_quoted_vec <- function(items, indent = "    ", width = 74) {
  q <- sprintf('"%s"', items)
  out <- character(0)
  cur <- character(0)
  curlen <- nchar(indent)
  for (tok in q) {
    toklen <- nchar(tok) + 2L            # ", "
    if (length(cur) > 0L && curlen + toklen > width) {
      out <- c(out, paste0(indent, paste(cur, collapse = ", "), ","))
      cur <- character(0); curlen <- nchar(indent)
    }
    cur <- c(cur, tok); curlen <- curlen + toklen
  }
  if (length(cur) > 0L) out <- c(out, paste0(indent, paste(cur, collapse = ", ")))
  out
}


#' Build the data-loading code block for an uploaded + formatted dataset
#'
#' Pretty-printed: the (possibly long) column vector and the dataFormat()
#' arguments are wrapped and indented.
#'
#' @param file_hint uploaded file name (used in read.csv path)
#' @param cols selected columns (ID first if present)
#' @param has_id whether an ID column is included (then id = 1)
#' @param na_code numeric NA code or NULL
#' @param resp_type response type string or NULL (auto)
#' @param ca numeric correct-answer vector (rated data) or NULL
#' @noRd
script_block_upload <- function(file_hint, cols, has_id, na_code, resp_type, ca = NULL) {
  args <- character(0)
  if (isTRUE(has_id)) args <- c(args, "id = 1")
  if (!is.null(na_code)) args <- c(args, sprintf("na = %s", na_code))
  if (!is.null(resp_type)) args <- c(args, sprintf('response.type = "%s"', resp_type))
  if (!is.null(ca)) args <- c(args, sprintf("CA = c(%s)", paste(ca, collapse = ", ")))

  lines <- c(
    sprintf('raw <- read.csv("%s")', file_hint %||% "your_data.csv"),
    "dat <- dataFormat(",
    "  raw[, c(",
    wrap_quoted_vec(cols, indent = "    "),
    if (length(args)) "  )]," else "  )]"
  )
  if (length(args)) {
    for (i in seq_along(args)) {
      lines <- c(lines, paste0("  ", args[i], if (i < length(args)) "," else ""))
    }
  }
  c(lines, ")")
}
